#!/usr/bin/python
import sys
import socket
import re

# read in username and password
USERNAME = sys.argv[1]
PASSWORD = sys.argv[2]
HOSTNAME = 'fring.ccs.neu.edu'

# connect to host on http port
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((HOSTNAME, 80))

# get request to get csrf and session tokens
GET_LOGIN_COOKIES = "GET /accounts/login/?next=/fakebook/ HTTP/1.1 \r\n" \
                    "Host: {0}\r\n\r\n".format(HOSTNAME)

# send request for login cookies
sock.send(GET_LOGIN_COOKIES)

msg = sock.recv(4096)

sock.close()


# use regular expressions to parse out csrf and session tokens
cookies = re.findall(r'Set-Cookie: (.*?);', msg)
csrf_cookie = cookies[0]
session_cookie = cookies[1]
csrf_token = re.search(r'csrftoken=(.*?);', msg).group(1)
#session_cookie = re.findall(r'Set-Cookie: (.*?);', msg)[1]

print session_cookie

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((HOSTNAME, 80))

login_data = "csrfmiddlewaretoken={0};username={1};password={2}".format(csrf_token, USERNAME, PASSWORD)

# login to fakebook account
LOGIN = "POST /accounts/login/?next=/fakebook/ HTTP/1.1 \n" \
        "Host: fring.ccs.neu.edu\n" \
        "Cookie: {0}; {1}\n" \
        "Content-Type: application/x-www-form-urlencoded\n" \
        "Content-Length: {2}\n" \
        "Origin: fring.ccs.neu.edu\n" \
        "Content-Language: en-us\n" \
        "Referer: /accounts/login/?next=/fakebook/\n\n" \
        "csrfmiddlewaretoken={5};username={3};password={4};\r\n".format(csrf_cookie, session_cookie, str(len(login_data)), USERNAME, PASSWORD, csrf_token)
sock.send(LOGIN)

msg = sock.recv(4096)

print msg

cookies = re.findall(r'Set-Cookie: (.*?);', msg)
session_cookie = cookies[0]

sock.close()

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((HOSTNAME, 80))

GET_MAIN_PAGE = "GET http://fring.ccs.neu.edu/fakebook/ HTTP/1.1 \r\n" \
                "Host: {0}\r\n" \
                "Cookie: {1}\r\n\r\n".format(HOSTNAME, session_cookie)

sock.send(GET_MAIN_PAGE)

msg = sock.recv(4096)

print msg
